<?php
/**
 * TL_ROOT/system/modules/secure_accessdata/languages/de/default.php 
 * 
 * Contao extension: secure_accessdata 1.0.0 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Daniel Kiesel 
 * License   : LGPL 
 * Author    : Daniel Kiesel (iCodr8) 
 * Translator: Daniel Kiesel (iCodr8) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['SADTY']['project']['0'] = "Projekt";
$GLOBALS['TL_LANG']['SADTY']['project']['1'] = "Sichere Zugangsdaten für ein Projekt.";
$GLOBALS['TL_LANG']['SADTY']['weblogin']['0'] = "Web Login";
$GLOBALS['TL_LANG']['SADTY']['weblogin']['1'] = "Sichere Zugangsdaten für einen Web Login.";
$GLOBALS['TL_LANG']['SADTY']['mail']['0'] = "E-Mail Account";
$GLOBALS['TL_LANG']['SADTY']['mail']['1'] = "Sichere Zugangsdaten für einen E-Mail Account.";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['ftp']['0'] = "FTP";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['ftp']['1'] = "FTP";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['sftp']['0'] = "SFTP";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['sftp']['1'] = "SFTP";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['ftp_ssl_implicit']['0'] = "FTP mit SSL (Implizit)";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['ftp_ssl_implicit']['1'] = "FTP mit SSL (Implizit)";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['ftp_tls_ssl']['0'] = "FTP mit TLS/SSL";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['ftp_tls_ssl']['1'] = "FTP mit TLS/SSL";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['webdav']['0'] = "WEBDAV";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['webdav']['1'] = "WEBDAV";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['webdav_https']['0'] = "WEBDAV HTTPS";
$GLOBALS['TL_LANG']['SAD_FTP_PROTOCOL']['webdav_https']['1'] = "WEBDAV HTTPS";
 
?>
