<?php
/**
 * TL_ROOT/system/modules/secure_accessdata/languages/de/modules.php 
 * 
 * Contao extension: secure_accessdata 1.0.0 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Daniel Kiesel 
 * License   : LGPL 
 * Author    : Daniel Kiesel (iCodr8) 
 * Translator: Daniel Kiesel (iCodr8) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['tl_secure_accessdata']['0'] = "Sichere Zugangsdaten";
$GLOBALS['TL_LANG']['MOD']['tl_secure_accessdata']['1'] = "In diesem Modul können Zugangsdaten für verschiedene Zugangsarten verschlüsselt abgelegt werden.";
 
?>
