<?php
/**
 * TL_ROOT/system/modules/secure_accessdata/languages/de/tl_secure_accessdata.php 
 * 
 * Contao extension: secure_accessdata 1.0.0 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Daniel Kiesel 
 * License   : LGPL 
 * Author    : Daniel Kiesel (iCodr8) 
 * Translator: Daniel Kiesel (iCodr8) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_secure_accessdata']['label_callback_protect'] = "Geschützt";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['label_callback_protect_users'] = "User";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['label_callback_protect_groups'] = "Gruppen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['access_title']['0'] = "Sichere Zugangsdaten Name";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['access_title']['1'] = "Sichere Zugangsdaten Name";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['type']['0'] = "Typ";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['type']['1'] = "Hier wird der Zugangsdaten-Typ gewählt.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['author']['0'] = "Autor";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['author']['1'] = "Autor dieser Zugangsdaten.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['protect']['0'] = "Zugriff schützen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['protect']['1'] = "Hier können Sie diese Zugangsdaten nur für bestimmte User und Gruppen freigeben.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['protect_users']['0'] = "User mit Zugriff";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['protect_users']['1'] = "Wählen Sie hier die User aus, die Zugriff auf diese Zugangsdaten haben dürfen.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['protect_groups']['0'] = "Gruppen mit Zugriff";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['protect_groups']['1'] = "Wählen Sie hier die Gruppen aus, die Zugriff auf diese Zugangsdaten haben dürfen.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['info']['0'] = "Zusatz Informationen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['info']['1'] = "Hier können weitere Zugangsdaten eingetragen werden, die nicht in die anderen Felder passen.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['weblogin_url']['0'] = "Login URL";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['weblogin_url']['1'] = "Hier wird die komplette URL zum Login hinterlegt.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['weblogin_name']['0'] = "Benutzername";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['weblogin_name']['1'] = "Der Benutzername des Login.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['weblogin_pwd']['0'] = "Passwort";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['weblogin_pwd']['1'] = "Das zum Benutzernamen passende Passwort.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['contao_user']['0'] = "Contao Benutzername";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['contao_user']['1'] = "Der Benutzername der Contao Installation.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['contao_pwd']['0'] = "Contao Passwort";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['contao_pwd']['1'] = "Das zum Benutzernamen passende Passwort.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['contao_install_pwd']['0'] = "Contao installations Passwort";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['contao_install_pwd']['1'] = "Das Passwort für die Contao Installation.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['url']['0'] = "URL";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['url']['1'] = "Hier wird die komplette URL angegeben.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['root']['0'] = "Root";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['root']['1'] = "Hier wird die Adresse zum Root angegeben.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_server']['0'] = "Datenbank Server";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_server']['1'] = "Datenbank Server (Standard: \"localhost\").";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_name']['0'] = "Datenbank Name";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_name']['1'] = "Datenbank Name.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_user']['0'] = "Datenbank User";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_user']['1'] = "Datenbank User.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_pwd']['0'] = "Datenbank Passwort";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_pwd']['1'] = "Das zum Datenbank User passende Passwort.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_charset']['0'] = "Datenbank Zeichensatz";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_charset']['1'] = "Datenbank Zeichensatz (Standard: \"UTF-8\").";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_port']['0'] = "Datenbank Port";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['db_port']['1'] = "Datenbank Port (Standard: \"3306\").";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_server']['0'] = "FTP Server";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_server']['1'] = "FTP Server.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_user']['0'] = "FTP User";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_user']['1'] = "FTP User.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_pwd']['0'] = "FTP Passwort";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_pwd']['1'] = "FTP Passwort.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_protocol']['0'] = "FTP Protokoll";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_protocol']['1'] = "FTP Protokoll (Standard: \"FTP\").";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_port']['0'] = "FTP Port";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ftp_port']['1'] = "FTP Port (Standard: \"21\").";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ssh_server']['0'] = "SSH Server";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ssh_server']['1'] = "SSH Server.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ssh_port']['0'] = "SSH Port";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ssh_port']['1'] = "SSH Port (Standard: \"22\").";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ssh_user']['0'] = "SSH User";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ssh_user']['1'] = "SSH User.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ssh_pwd']['0'] = "SSH Passwort";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['ssh_pwd']['1'] = "SSH Passwort.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['webadmin_url']['0'] = "Webadmin Login URL";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['webadmin_url']['1'] = "Hier wird die komplette URL zum Webadmin Login hinterlegt.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['webadmin_name']['0'] = "Benutzername";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['webadmin_name']['1'] = "Der Benutzername des Webadmin Login.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['webadmin_pwd']['0'] = "Passwort";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['webadmin_pwd']['1'] = "Das zum Benutzernamen passende Passwort.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_name']['0'] = "E-Mail Name";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_name']['1'] = "Name des E-Mail Account Besitzer.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_email']['0'] = "E-Mail Adresse";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_email']['1'] = "E-Mail Adresse.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_loginname']['0'] = "Login Name";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_loginname']['1'] = "Login Name.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_pwd']['0'] = "Passwort";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_pwd']['1'] = "Das zum Login Name passende Passwort.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_crypt']['0'] = "Verschlüsselungsmethode";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_crypt']['1'] = "Verschlüsselungsmethode.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_smtp_host']['0'] = "E-Mail SMTP Host";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_smtp_host']['1'] = "E-Mail SMTP Host.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_smtp_port']['0'] = "E-Mail SMTP Port";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_smtp_port']['1'] = "E-Mail SMTP Port.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_imap_host']['0'] = "E-Mail IMAP Host";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_imap_host']['1'] = "E-Mail IMAP Host.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_imap_port']['0'] = "E-Mail IMAP Port";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_imap_port']['1'] = "E-Mail IMAP Port.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_pop_host']['0'] = "E-Mail POP Host";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_pop_host']['1'] = "E-Mail POP Host.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_pop_port']['0'] = "E-Mail POP Port";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_pop_port']['1'] = "E-Mail POP Port.";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['title_legend'] = "Titel und Typ";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['protect_legend'] = "Zugriff Schützen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['info_legend'] = "Zusätzliche Informationen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['weblogin_legend'] = "Web Login Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['contao_legend'] = "Contao Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['local_legend'] = "Lokale Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['local_db_legend'] = "Lokale Datenbank Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['preview_legend'] = "Preview Allgemeine Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['preview_db_legend'] = "Preview Datenbank Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['preview_ftp_legend'] = "Preview FTP Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['preview_ssh_legend'] = "Preview SSH Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['online_legend'] = "Online Allgemeine Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['online_db_legend'] = "Online Datenbank Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['online_ftp_legend'] = "Online FTP Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['online_ssh_legend'] = "Online SSH Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['webadmin_legend'] = "Webadmin Zugangsdaten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_legend'] = "E-Mail";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_smtp_legend'] = "E-Mail (SMTP)";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_imap_legend'] = "E-Mail (IMAP)";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['mail_pop_legend'] = "E-Mail (POP)";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['new']['0'] = "Neue Zugangsdaten anlegen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['new']['1'] = "Neue Zugangsdaten anlegen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['edit']['0'] = "Zugangsdaten bearbeiten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['edit']['1'] = "Zugangsdaten ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['copy']['0'] = "Zugangsdaten duplizieren";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['copy']['1'] = "Zugangsdaten ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['delete']['0'] = "Zugangsdaten löschen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['delete']['1'] = "Zugangsdaten ID %s löschen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['show']['0'] = "Zugangsdaten anzeigen";
$GLOBALS['TL_LANG']['tl_secure_accessdata']['show']['1'] = "Zugangsdaten ID %s anzeigen";
 
?>
